/* Generated By:JavaCC: Do not edit this line. statementsConstants.java */
package statements;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface statementsConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SINGLE_LINE_COMMENT = 5;
  /** RegularExpression Id. */
  int MULTI_LINE_COMMENT = 6;
  /** RegularExpression Id. */
  int COMMA = 7;
  /** RegularExpression Id. */
  int AT = 8;
  /** RegularExpression Id. */
  int FULLSTOP = 9;
  /** RegularExpression Id. */
  int UNDERSCORE = 10;
  /** RegularExpression Id. */
  int SINGLEQUOTE = 11;
  /** RegularExpression Id. */
  int VERTICALBAR = 12;
  /** RegularExpression Id. */
  int DOUBLEQUOTE = 13;
  /** RegularExpression Id. */
  int AMPERSAND = 14;
  /** RegularExpression Id. */
  int BAKCSLASH = 15;
  /** RegularExpression Id. */
  int EQUALSTO = 16;
  /** RegularExpression Id. */
  int HASH = 17;
  /** RegularExpression Id. */
  int COLON = 18;
  /** RegularExpression Id. */
  int SEMICOLON = 19;
  /** RegularExpression Id. */
  int QUESTIONMARK = 20;
  /** RegularExpression Id. */
  int PLUS = 21;
  /** RegularExpression Id. */
  int MINUS = 22;
  /** RegularExpression Id. */
  int MULTIPLY = 23;
  /** RegularExpression Id. */
  int DIVIDE = 24;
  /** RegularExpression Id. */
  int POWER = 25;
  /** RegularExpression Id. */
  int MODULUS = 26;
  /** RegularExpression Id. */
  int IF = 27;
  /** RegularExpression Id. */
  int ELSE = 28;
  /** RegularExpression Id. */
  int PRINT = 29;
  /** RegularExpression Id. */
  int PRINTLN = 30;
  /** RegularExpression Id. */
  int FOREACH = 31;
  /** RegularExpression Id. */
  int WHILE = 32;
  /** RegularExpression Id. */
  int FUNCTION = 33;
  /** RegularExpression Id. */
  int RETURN = 34;
  /** RegularExpression Id. */
  int PROCEDURE = 35;
  /** RegularExpression Id. */
  int INPUT = 36;
  /** RegularExpression Id. */
  int IN = 37;
  /** RegularExpression Id. */
  int OBJECTTYPE = 38;
  /** RegularExpression Id. */
  int TRUE = 39;
  /** RegularExpression Id. */
  int FALSE = 40;
  /** RegularExpression Id. */
  int VOID = 41;
  /** RegularExpression Id. */
  int CONSTANT = 42;
  /** RegularExpression Id. */
  int VARIABLENAME = 43;
  /** RegularExpression Id. */
  int FLOAT = 44;
  /** RegularExpression Id. */
  int STRING = 45;
  /** RegularExpression Id. */
  int SPECIALCHARACTERS = 46;
  /** RegularExpression Id. */
  int LP = 47;
  /** RegularExpression Id. */
  int RP = 48;
  /** RegularExpression Id. */
  int LGP = 49;
  /** RegularExpression Id. */
  int RGP = 50;
  /** RegularExpression Id. */
  int LSP = 51;
  /** RegularExpression Id. */
  int RSP = 52;
  /** RegularExpression Id. */
  int AND = 53;
  /** RegularExpression Id. */
  int OR = 54;
  /** RegularExpression Id. */
  int XOR = 55;
  /** RegularExpression Id. */
  int NOT = 56;
  /** RegularExpression Id. */
  int GT = 57;
  /** RegularExpression Id. */
  int LT = 58;
  /** RegularExpression Id. */
  int EQ = 59;
  /** RegularExpression Id. */
  int LTE = 60;
  /** RegularExpression Id. */
  int GTE = 61;
  /** RegularExpression Id. */
  int NE = 62;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "<SINGLE_LINE_COMMENT>",
    "<MULTI_LINE_COMMENT>",
    "\",\"",
    "\"@\"",
    "\".\"",
    "\"_\"",
    "\"\\\'\"",
    "\"|\"",
    "\"\\\"\"",
    "\"&\"",
    "\"\\\\\"",
    "\"=\"",
    "\"#\"",
    "\":\"",
    "\";\"",
    "\"?\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"**\"",
    "\"%\"",
    "\"if\"",
    "\"else\"",
    "\"print\"",
    "\"println\"",
    "\"foreach\"",
    "\"while\"",
    "\"function\"",
    "\"return\"",
    "\"procedure\"",
    "\"input\"",
    "\"in\"",
    "<OBJECTTYPE>",
    "\"true\"",
    "\"false\"",
    "\"void\"",
    "<CONSTANT>",
    "<VARIABLENAME>",
    "<FLOAT>",
    "<STRING>",
    "<SPECIALCHARACTERS>",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\"&&\"",
    "\"||\"",
    "\"^\"",
    "\"!\"",
    "\">\"",
    "\"<\"",
    "\"==\"",
    "\"<=\"",
    "\">=\"",
    "\"!=\"",
  };

}
